### ISSUE TITLE
Is it possible to make support of graphile/postgraphile?

### ISSUE THREAD

**Issue by ayvanov** [vuex-orm/plugin-graphql#65] opened 2018-10-26 11:26 UTC
Hello, thanks for the great plugin!

I was wondering if it's possible to make it compatible with https://github.com/graphile/postgraphile tool?
It makes a graphql api from existing postgresql tables. This tandem would be awesome. 

Data retrieving is working already, but there are minor differences in mutations, for example postraphile makes it this way:
```

input TodoInput {
  id: Int
  label: String!
  isCompleted: Boolean
}

input CreateTodoInput {
  clientMutationId: String
  todo: TodoInput!
}

type Mutation {
  createTodo(
    input: CreateTodoInput!
  ): CreateTodoPayload

```
...and so on.

**Comment by phortx** [comment] 2018-10-26 11:30
It would be awesome when this plugin is compatible to as much API designs as possible.

Unfortunately there is no real standard and every lib and every app cooks its own soup :(

However I'm very open and thankful for Pull Requests to support other libs :)

**Comment by ayvanov** [comment] 2018-10-26 11:35
Ok, I will give it a try :)

**Comment by phortx** [comment] 2018-10-26 12:52
Very nice! When you need help, please ask. You can also our slack channel for quick discussions ;)

I think we have to change the heuristics that analyze the schema and change how the queries are generated based on that. A good starting point is to look at the `connectionMode`.

However I advice you to wait until I have merged #66 because that touches every file of the project and you'll get in conflict hell when you start working before I have finished that :D

**Comment by ayvanov** [comment] 2018-10-26 14:59
Ok, thank's for the info

**Comment by phortx** [comment] 2018-11-15 14:51
#66 is merged now.

**Comment by ayvanov** [comment] 2018-11-15 19:34
Good joob! ;)

**Comment by kevinmarrec** [comment] 2019-03-08 00:55
@aynanov Did you begin some work regarding `postgraphile` support ? Or did you find an alternative ?

@phortx What are now the advices/guidelines to work on this eventual support as #66 has been merged ? I mean where should I start if I take the time to dive into in coming weeks ?

**Comment by ayvanov** [comment] 2019-03-09 06:35
No, I did not begin (

**Comment by phortx** [comment] 2019-03-23 06:50
@kevinmarrec nothing special here :) the README describes anything relevant how to work with the repo. Just give it a try and ask when something is bothering you :) Thanks!

**Comment by phortx** [comment] 2019-04-25 12:25
https://github.com/vuex-orm/plugin-graphql/pull/89 should bring everything we need for this :)

**Comment by kevinmarrec** [comment] 2019-04-25 13:25
@phortx Good stuff ! Will take a look :D

**Comment by phortx** [comment] 2019-04-30 12:31
Merged (but not released yet). I close this, feel free to reopen if the problem isn't solved for you :)

**Closed by phortx** 2019-04-30 12:31 UTC
Labels: enhancement
